#include <allegro.h>
/* XPM */
static const char *allegico_xpm[] = {
/* columns rows colors chars-per-pixel */
"48 48 148 2",
"   c #009D00",
".  c #00A200",
"X  c #02A300",
"o  c #05A000",
"O  c #00A700",
"+  c #02A600",
"@  c #03A700",
"#  c #00A706",
"$  c #01A800",
"%  c #00A900",
"&  c #00A901",
"*  c #02A900",
"=  c #00AA00",
"-  c #00AB00",
";  c #02AA00",
":  c #03AA00",
">  c #02AB00",
",  c #00A902",
"<  c #00AB02",
"1  c #04AB00",
"2  c #00AC00",
"3  c #01AC00",
"4  c #00AD00",
"5  c #00AC01",
"6  c #02AC00",
"7  c #02AD00",
"8  c #00AE00",
"9  c #01AE00",
"0  c #00AF00",
"q  c #00AD03",
"w  c #00AF02",
"e  c #00AF03",
"r  c #05AC00",
"t  c #04AE00",
"y  c #07AE00",
"u  c #00A904",
"i  c #00B000",
"p  c #01B000",
"a  c #00B100",
"s  c #00B001",
"d  c #00B101",
"f  c #03B000",
"g  c #03B100",
"h  c #01B200",
"j  c #00B300",
"k  c #01B300",
"l  c #00B201",
"z  c #00B301",
"x  c #03B300",
"c  c #00B102",
"v  c #00B003",
"b  c #00B103",
"n  c #00B302",
"m  c #00B203",
"M  c #06B100",
"N  c #04B300",
"B  c #00B400",
"V  c #01B400",
"C  c #01B500",
"Z  c #00B401",
"A  c #02B400",
"S  c #03B400",
"D  c #02B500",
"F  c #00B600",
"G  c #01B600",
"H  c #00B700",
"J  c #00B601",
"K  c #00B701",
"L  c #02B600",
"P  c #03B700",
"I  c #00B402",
"U  c #00B403",
"Y  c #04B400",
"T  c #05B500",
"R  c #05B600",
"E  c #04B700",
"W  c #06B600",
"Q  c #00B204",
"!  c #00B505",
"~  c #00B604",
"^  c #00B704",
"/  c #00B800",
"(  c #01B800",
")  c #00B900",
"_  c #01B900",
"`  c #03B800",
"'  c #03B900",
"]  c #00BA00",
"[  c #00BB00",
"{  c #01BB00",
"}  c #00BA01",
"|  c #00BB01",
" . c #02BB00",
".. c #00B902",
"X. c #00BA03",
"o. c #00BB03",
"O. c #04B900",
"+. c #00BC00",
"@. c #01BC00",
"#. c #00BD00",
"$. c #01BD00",
"%. c #00BD01",
"&. c #02BD00",
"*. c #00BE00",
"=. c #01BE00",
"-. c #00BF00",
";. c #01BF00",
":. c #00BE01",
">. c #00BF01",
",. c #02BE00",
"<. c #03BE00",
"1. c #02BF00",
"2. c #00BC02",
"3. c #00BD02",
"4. c #00BC03",
"5. c #00BE02",
"6. c #00BF02",
"7. c #05BC00",
"8. c #04BD00",
"9. c #05BE00",
"0. c #07BE00",
"q. c #00BD04",
"w. c #00C000",
"e. c #01C000",
"r. c #00C100",
"t. c #01C100",
"y. c #00C001",
"u. c #00C101",
"i. c #02C000",
"p. c #02C100",
"a. c #00C200",
"s. c #01C200",
"d. c #00C300",
"f. c #01C300",
"g. c #00C201",
"h. c #00C301",
"j. c #02C200",
"k. c #03C200",
"l. c #00C002",
"z. c #00C102",
"x. c #00C202",
"c. c #04C000",
"v. c #04C100",
"b. c #00C400",
"n. c #00C004",
"m. c #00C204",
"M. c #00C00A",
"N. c None",
/* pixels */
"N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.~ y z :.e.X.t t N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.H X.e.e.e.e.e.e.:.X.H N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.t H :.e.e.:.e.:.e.e.:.:.X.Q N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.t X.:.e.e.e.:.e.:.:.:.e.:.e.:.N N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.X.e.e.e.e.:.e.:.e.e.e.:.:.:.e.7.z N.N.N.N.N.N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.H :.e.:.e.e.:.e.:.e.e.:.:.e.e.:.:.z N.N.N.N.N.N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.H H e.:.:.:.e.e.:.e.e.e.e.:.:.e.:.e.:.t N.N.N.N.N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.z e.e.e.e.e.e.e.:.:.e.:.:.:.:.e.:.e.:.H N.N.N.N.N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.N.N.N.H X.e.m.m.e.e.e.:.e.e.:.e.e.e.e.:.:.e.:.:.t N.N.N.N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.N.N.N.z e.:.e.:.:.e.e.:.e.e.:.e.:.e.:.e.:.:.:.:.7.N.N.N.N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.N.N.H H :.:.:.:.:.e.:.e.:.:.e.:.e.:.e.:.e.:.:.:.X.z N.N.N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.N.N.z :.e.e.:.:.:.:.e.:.e.e.:.e.:.e.:.e.:.:.e.e.e.Y N.N.N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.N.N.X.e.:.:.e.:.e.e.:.e.:.:.e.:.e.:.e.:.e.:.e.:.:.:.N.N.N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.N.r X.e.e.v.:.e.:.e.e.e.:.e.:.e.:.e.:.e.:.:.e.e.e.X.N.N.N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.N.7.:.:.:.e.e.e.:.:.e.:.e.:.e.:.e.:.e.:.e.e.:.:.e.:.Y N.N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.N.:.:.e.:.:.:.:.e.:.e.:.e.:.e.:.e.:.e.:.e.:.e.e.b.:.q N.N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.N.X.e.:.e.:.e.:.e.e.:.e.:.e.:.e.:.e.:.e.:.:.e.e.e.7.z N.N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.N.X.:.e.e.e.e.e.e.:.e.:.e.:.e.:.e.:.e.:.e.:.e.e.e.c.Y N.N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.H X.:.:.e.e.e.:.e.e.:.e.:.e.:.e.:.e.:.e.:.e.:.m.m.e.7.N.N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.H :.:.:.:.:.e.e.e.:.e.:.e.e.:.e.:.:.e.:.e.e.:.e.e.e.X.N.N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.H :.e.:.:.e.:.:.e.e.:.e.:.:.e.:.e.e.:.e.:.e.:.e.e.e.:.Y N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.H :.v.e.:.e.:.e.:.e.e.:.e.e.e.e.:.:.:.:.:.e.:.e.:.e.e.t N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.H e.:.:.:.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.:.+ N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.> N N H N H Y N H Y Y N H H N H N z Y H z z N Y z z z X N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.  > > u > > > > t > > > > > 1 > > > > > > > > t > > > > t N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.z :.:.:.:.:.:.:.X.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.X.:.:.:.X.t N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.t e.e.e.:.:.:.:.e.:.e.e.:.:.e.:.:.:.:.:.e.:.e.e.:.e.:.:.H N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.H :.b.e.:.:.e.e.e.:.e.e.e.:.e.:.e.e.e.e.e.e.e.:.e.e.e.e.> N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.X.:.e.:.:.e.:.:.:.e.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.e.:.Q N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.H 7.7.e.e.:.e.:.e.:.e.e.e.:.e.e.e.:.e.:.e.:.:.e.v.X.H N.N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.Q X.:.e.e.:.:.:.:.e.e.e.:.e.:.:.e.e.:.e.:.e.:.v.e.:.z N.N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.N.z X.e.e.:.:.:.:.:.:.:.e.e.e.e.:.e.e.:.:.e.:.:.e.z N.N.N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.N.N.H :.e.:.e.e.:.e.:.e.e.:.e.e.:.e.e.:.:.e.:.e.X.H N.N.N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.N.N.N.z X.:.:.e.:.:.e.e.:.e.e.:.:.:.:.:.e.:.e.X.z N.N.N.N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.t :.e.e.:.e.e.:.:.e.e.:.e.e.:.:.e.e.H t N.N.N.N.N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.> X.:.e.:.:.:.:.e.:.:.e.:.:.:.:.z H N.N.N.N.N.N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.t H X.:.:.:.e.:.:.:.:.:.X.H > N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.z H :.7.v.X.~ H ~ N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.N.N.# X + y N.N.N.N.N.b.X.e.H N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N   X z H N.:.:.X.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.+ > q H 7.M.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.z t :.t t N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.q + > N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.",
"N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N."
};
//#if defined ALLEGRO_WITH_XWINDOWS && defined ALLEGRO_USE_CONSTRUCTOR
extern void *allegro_icon;
CONSTRUCTOR_FUNCTION(static void _set_allegro_icon(void));
static void _set_allegro_icon(void)
{
    allegro_icon = allegico_xpm;
}
//#endif
